### ISSUE TITLE
Possible to have functions with different Arity in the same Genotype?

### ISSUE THREAD

**Issue by sachag678** [kpot/cartgp#1]
In available functions can there be the following:

available_functions = [
    ("plus", lambda args: args[0] + args[1]), #arity = 2
    ("logical", lamda args: np.where(args[0]>args[1], args[2], args[3])) # arity = 4
]

I notice that the arity is defined in the Genotype so I am leaning toward it not being possible but maybe there is some functionality that I am not seeing?

Thanks!

**Comment by kpot** [comment]
Unfortunately, you are correct, it is not possible to have functions with different arity.
Not because it would be absolutely impossible to implement them, but because I was trying to stick to the canonical CGP and avoid over-complication.

**Comment by sachag678** [comment]
Fair enough. Thank you for the response!
